public class checkDataTypes {
    public void MethodBoolean() {
        Boolean checkBoolean = true;
        system.debug('check Boolean is '+ checkBoolean);

    }
    public void MethodInteger(){
        Integer varFirst =1;
        Integer varSecond =2;
        system.debug('var first is '+varFirst +' and ' +'var second is '+ varSecond);
    }
    public void Stringmethod(){
        String varName ='Name';
        String var2Name ='your name';
        system.debug(varName+' '+ var2Name);

    }
}